export { clients } from './clients'
export { fleet_thumbs } from './fleetThumbs'
export { menus } from './menu'
export { team } from './team'
export { projects } from './projects'
export { contacts } from './contacts'
export { fleet_details } from './fleet'
export { pdf } from './fleet'